const CLOSE_DIALOG = "CLOSE_DIALOG";
const SHOW_DIALOG = "SHOW_DIALOG";
const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const SET_USER = "SET_USER";
const SET_ERROR = "SET_ERROR";

export { CLOSE_DIALOG, SHOW_DIALOG, START_LOADING, SET_ERROR, STOP_LOADING, SET_USER };
